host: 0.0.0.0
port: 4001

plugins:
  - jekyll-sitemap

sass:
  style: compressed

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Guardfile'
  - 'LICENSE'
  - 'README.md'
  - 'vendor'

timezone: Europe/Stockholm
markdown: kramdown

live_url: https://whatistranshumanism.org
email: markus@polyscopic.works
discussion_group: https://groups.google.com/d/forum/whatistranshumanism
latest_commit: 1c953bc6a9ad8cc9908d2c855f5aec8fb2a21d12
author: Markus Amalthea Magnuson
