gems:
  - jekyll-sitemap

sass:
  style: compressed

timezone: Europe/Stockholm
markdown: kramdown

live_url: https://whatistranshumanism.org
live_hostname: whatistranshumanism.org
email: info@whatistranshumanism.org
discussion_group: https://groups.google.com/d/forum/whatistranshumanism
google_analytics_id: UA-49520727-1
latest_commit: 3b09d5157e6b266244c31d20639dba2f1a7af20f
