safe: true
timezone: Europe/Stockholm

baseurl: /whatistranshumanism.org
live_url: http://whatistranshumanism.org
live_hostname: whatistranshumanism.org
google_analytics_id: UA-49520727-1
latest_commit: fc9ffd644fc58445b93aafcc9d90b998c5ae8a15

translations_email: translations@whatistranshumanism.org
