baseURL: https://transhumanism.netlify.com/
canonifyURLs: false
cleanDestinationDir: true
copyright: Public Domain
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
metaDataFormat: yaml
noTimes: true
publishDir: dist
relativeURLs: true
verbose: false
watch: true

params:
  username: humanityplus
  license: https://creativecommons.org/publicdomain/zero/1.0
  publisher: 
    name: Humanity
    links:
      twitter: https://twitter.com/humanityplus
      website: https://humanityplus.org
      wikipedia: https://en.wikipedia.org/wiki/Humanity%2B

  links:
    github: https://github.com/iinfin/whatistranshumanism.org

languages:
  en:
    languageCode: en-us
    languageLang: en
    languageName: English
    weight: 0
    params:
